config/routes.rb
Rails.application.routes.draw do

  root 'compliments#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create', as: :oauth_callback
  get 'auth/failure', to: redirect('/')
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  resources :compliments do
    get :received, on: :collection
    get :given, on: :collection
    get :random, on: :collection
    post :slack, on: :collection

    resource :upheart, only: [:create, :destroy]
  end

  resources :quotes do
    post :slack, on: :collection
    get :given, on: :collection
    get :attributed, on: :collection
    get :random, on: :collection
  end

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :quoter, class_name: "User"
  belongs_to :quotee, class_name: "User"

  validates :quoter, presence: true
  validates :quotee, presence: true

  default_scope { order("created_at DESC") }

  delegate :name, to: :quotee, prefix: true
  delegate :name, to: :quoter, prefix: true

  delegate :image, to: :quotee, prefix: true
  delegate :image, to: :quoter, prefix: true

  delegate :slack_id, to: :quotee, prefix: true
  delegate :slack_id, to: :quoter, prefix: true

  delegate :slack_username, to: :quotee, prefix: true
  delegate :slack_username, to: :quoter, prefix: true

  after_create :post_to_slack

  def from?(user)
    quoter_id == user.id
  end

  def self.random
    unscoped.order("RANDOM()").first
  end

  private

  def post_to_slack
    Slack.notify_quote(self)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:random, :slack]
  skip_before_filter :verify_authenticity_token, only: [:slack]

  http_basic_authenticate_with name: "internals", password: ENV["RANDOM_QUOTES_PASSWORD"], only: :random

  before_filter :validate_slack_token, only: :slack

  before_action :find_quote, only: [:show, :edit, :update, :destroy]

  def index
    @quotes = Quote.all
  end

  def given
    @quotes = current_user.quotes_given
    render :index
  end

  def attributed
    @quotes = current_user.quotes_attributed
    render :index
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      redirect_to quotes_path
    else
      render :new
    end
  end

  def slack
    quote_command = SlashCommand::Quote.new(user_id: params[:user_id], text: params[:text])

    @quote = Quote.new(
      quoter: quote_command.quoter,
      quotee: quote_command.quotee,
      text: quote_command.quote
    )

    if @quote.save
      render text: "Posted your quote!"
    else
      render text: "Oops! Something went wrong :("
    end
  end

  def show
  end

  def random
    @quote = Quote.random

    render :show
  end

  def edit
  end

  def update
    if @quote.update_attributes(quote_params)
      redirect_to quotes_path
    else
      render :edit
    end
  end

  def destroy
    if @quote.destroy
      redirect_to quotes_path
    else
      render :show
    end
  end

  private

  def find_quote
    @quote = Quote.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:quoter_id, :quotee_id, :text)
  end

  def validate_slack_token
    # render text: 'Nope!', status: 401 if params[:token] != ENV['SLACK_QUOTES_TOKEN']
  end
end

app/views/quotes/_form.html.haml
= simple_form_for @quote, html: { class: 'form' } do |f|
  = f.hidden_field :quoter_id, value: current_user.id

  %fieldset.form-field
    = f.association :quotee, input_html: { class: 'form-select' }, label_html: { class: 'form-label' }
  %fieldset.form-field
    = f.input :text, as: :text, input_html: { class: 'form-input', rows: '5' }, label_html: { class: 'form-label' }

  = f.submit class: "btn"

app/views/quotes/_quote.html.haml
.message

  %p.message-date
    %em= quote.created_at.strftime("%B %d, %Y")

  = image_tag quote.quotee.image, class: "thumb message-avatar", size: "50"

  .card.message-content
    %p.message-content-name= quote.quotee.name
    = emojify(quote.text)

  .message-meta.group

    - if quote.from?(current_user)
      %ul.list.list--inline.message-controls
        %li.list-item= link_to "Edit", edit_quote_path(quote)
        %li.list-item= link_to "Delete", quote_path(quote), method: :delete

    %p.fr
      %span.tcs via
      = quote.quoter.name

app/views/quotes/edit.html.haml
= render 'form'

app/views/quotes/index.html.haml
.split.mbl
  .split-cell

    %ul.list.list--inline.list--inline--l
      .list-item= link_to "All", quotes_path, class: "list-item-link #{active_class(quotes_path)}"
      .list-item= link_to "Given", given_quotes_path, class: "list-item-link #{active_class(given_quotes_path)}"
      .list-item= link_to "Attributed", attributed_quotes_path, class: "list-item-link #{active_class(attributed_quotes_path)}"

  .split-cell

    = link_to "New Quote", new_quote_path, class: "btn"

- unless @quotes.empty?
  .g.collection.collection--1of2
    - @quotes.each do |quote|
      .g-b.g-b--1of2.collection-item
        = render quote
- else
  %p.pal.tac.tcs.tsi There are no quotes currently. Listen carefully :)

app/views/quotes/new.html.haml
= render partial: 'form'

app/views/quotes/show.html.haml
.cell.cell--s.well.well--l
  = render @quote