config/routes.rb
Rails.application.routes.draw do

  root 'compliments#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create', as: :oauth_callback
  get 'auth/failure', to: redirect('/')
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  resources :compliments do
    get :received, on: :collection
    get :given, on: :collection
    get :random, on: :collection
    post :slack, on: :collection

    resource :upheart, only: [:create, :destroy]
  end

  resources :quotes do
    post :slack, on: :collection
    get :given, on: :collection
    get :attributed, on: :collection
    get :random, on: :collection
  end

end

app/models/compliment.rb
class Compliment < ActiveRecord::Base
  belongs_to :complimenter, class_name: "User"
  belongs_to :complimentee, class_name: "User"
  has_many :uphearts, inverse_of: :compliment

  after_create :post_to_slack
  after_create :create_complimenter_upheart

  delegate :name, to: :complimentee, prefix: true
  delegate :name, to: :complimenter, prefix: true

  delegate :image, to: :complimentee, prefix: true
  delegate :image, to: :complimenter, prefix: true

  delegate :slack_id, to: :complimentee, prefix: true
  delegate :slack_id, to: :complimenter, prefix: true

  delegate :slack_username, to: :complimentee, prefix: true
  delegate :slack_username, to: :complimenter, prefix: true


  default_scope { order(created_at: :desc) }

  def self.public
    where(private: false)
  end

  def self.active
    joins("JOIN users AS complimentee ON complimentee.id = complimentee_id").
      joins("JOIN users AS complimenter ON complimenter.id = complimenter_id").
      where(complimentee: { active: true }).
      where(complimenter: { active: true })
  end

  def self.recent
    where("compliments.created_at > ?", 1.month.ago)
  end

  def self.random
    unscoped.active.recent.order("RANDOM()").first
  end

  def from?(user)
    user == complimenter
  end

  def notify
    ComplimentMailer.notify(self).deliver_later
  end

  def uphearted_by?(user)
    return false if user.nil?

    uphearts.select { |u| u.user_id = user.id }.any?
  end

  def upheart_count
    uphearts.size
  end

  private

  def post_to_slack
    Slack.notify_compliment(self) if ENV["SLACK_INCOMING_WEBHOOK"].present?
  end

  def create_complimenter_upheart
    self.uphearts.create(user_id: complimenter.id)
  end
end

app/controllers/compliments_controller.rb
require 'csv'

class ComplimentsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:random, :slack]
  skip_before_filter :verify_authenticity_token, only: [:slack]

  # before_filter :authenticate_ip, only: :random

  def index
    @compliments = Compliment.includes(
      :complimenter, :complimentee, :uphearts
    ).public.paginate(page: params[:page], per_page: 30)
  end

  def given
    @compliments = current_user.compliments_given.
      paginate(page: params[:page], per_page: 30)

    render :index
  end

  def received
    respond_to do |format|
      format.html do
        @compliments = current_user.compliments_received.
          paginate(page: params[:page], per_page: 30)

        render :index
      end
      format.csv do
        @compliments = current_user.compliments_received
        headers['Content-Disposition'] = "attachment; filename=\"compliments.csv\""
        headers['Content-Type'] ||= 'text/csv'
        @headers = ["From", "To", "Compliment", "When"]

        render :index
      end
    end

  end

  def new
    @compliment = current_user.compliments_given.new
  end

  def create
    @compliment = current_user.compliments_given.new(compliment_params)

    if @compliment.save
      redirect_to compliments_path
    else
      render :new
    end
  end

  def show
    @compliment = Compliment.find(params[:id])
  end

  def random
    @compliment = Compliment.public.random

    render :show
  end

  def slack
    compliment_command = SlashCommand::Compliment.new(user_id: params[:user_id], text: params[:text])

    @compliment = Compliment.new(
      complimenter: compliment_command.complimenter,
      complimentee: compliment_command.complimentee,
      text: compliment_command.compliment
    )

    if @compliment.save
      render text: "Posted your compliment!"
    else
      render text: "Oops! Something went wrong :("
    end
  end

  def edit
    @compliment = find_compliment
  end

  def update
    @compliment = find_compliment

    if @compliment.update_attributes(compliment_params)
      redirect_to compliments_path
    else
      render :edit
    end
  end

  def destroy
    @compliment = find_compliment

    if @compliment.destroy
      redirect_to compliments_path
    else
      render :show
    end
  end

  private

  def authenticate_ip
    if !((request.env["HTTP_X_FORWARDED_FOR"].try(:split, ',').try(:last) || request.env["REMOTE_ADDR"]) == '66.194.34.250')
      redirect_to '/'
    end
  end

  def find_compliment
    current_user.compliments_given.find(params[:id])
  end

  def compliment_params
    params.require(:compliment).permit(:complimentee_id, :text, :private)
  end
end

app/views/compliments/_compliment.html.haml
.message

  .tac
    .message-avatar.message-avatar--from
      .message-avatar-media
        = image_tag compliment.complimenter_image, class: "thumb--m", size: "50"
      .message-avatar-name.tcs
        @#{compliment.complimenter_slack_username}

    .message-arrow
      &rarr;

    .message-avatar
      .message-avatar-media
        = image_tag compliment.complimentee_image, class: "thumb--m", size: "50"
      .message-avatar-name.tcs
        @#{compliment.complimentee_slack_username}



  .card.message-content
    = emojify(compliment.text)

  .message-meta.group
    %ul.list.list--inline.message-controls.has-btn
      %li.list-item
        = link_to "#", class: "js-upheart-toggle #{'is-uphearted' if compliment.uphearted_by?(current_user)}", data: { upheart_url: compliment_upheart_url(compliment) } do
          ="&hearts;".html_safe
          %span.js-upheart-count= compliment.upheart_count
      - if compliment.from?(current_user)
        %li.list-item= link_to "Edit", edit_compliment_path(compliment)
        %li.list-item= link_to "Delete", compliment_path(compliment), method: :delete

    %p.message-date
      %em= compliment.created_at.strftime("%B %d, %Y")

app/views/compliments/_form.html.haml
= simple_form_for @compliment, html: { class: 'form' } do |f|

  %fieldset.form-field
    = f.association :complimentee, input_html: { class: 'form-select' }, label_html: { class: 'form-label' }
  %fieldset.form-field
    = f.input :text, as: :text, input_html: { class: 'form-input', rows: '5' }, label_html: { class: 'form-label' }

  = f.submit class: "btn"

app/views/compliments/edit.html.haml
= render partial: 'form'

app/views/compliments/index.csv.haml
= CSV.generate(headers: true) do |csv|
  - csv << @headers
  - @compliments.each do |compliment|
    - csv << [compliment.complimenter, compliment.complimentee, compliment.text.gsub(",", "，"), compliment.created_at.to_date]

app/views/compliments/index.html.haml
.split.mbm
  .split-cell

    %ul.list.list--inline.list--inline--l
      .list-item= link_to "All", compliments_path, class: "list-item-link #{active_class(compliments_path)}"
      .list-item= link_to "Given", given_compliments_path, class: "list-item-link #{active_class(given_compliments_path)}"
      .list-item= link_to "Received", received_compliments_path, class: "list-item-link #{active_class(received_compliments_path)}"

  .split-cell

    = link_to "New Compliment", new_compliment_path, class: "btn"
    = link_to "Download My Compliments", received_compliments_path(format: :csv), class: "btn"

- if @compliments.any?
  = will_paginate @compliments

  .g.collection.collection--1of2

    - @compliments.each do |compliment|
      .g-b.g-b--1of2.collection-item
        = render compliment


  = will_paginate @compliments
- else
  %p.pal.tac.tcs.tsi There are no compliments currently. Say something nice :)

app/views/compliments/show.html.haml
.cell.cell--s.well.well--l.tv
  = render @compliment

- if current_page?(random_compliments_path)
  %script
    setTimeout(function() { location.reload() }, 300000)