config/routes.rb
Rails.application.routes.draw do

  root 'compliments#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create', as: :oauth_callback
  get 'auth/failure', to: redirect('/')
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  resources :compliments do
    get :received, on: :collection
    get :given, on: :collection
    get :random, on: :collection
    post :slack, on: :collection

    resource :upheart, only: [:create, :destroy]
  end

  resources :quotes do
    post :slack, on: :collection
    get :given, on: :collection
    get :attributed, on: :collection
    get :random, on: :collection
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Compliments
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag('https://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700')
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
  %body{ class: body_class }
    %header.row.row--a.header
      .cell.well
        .g
          .g-b.g-b--1of2
            - if compliments?
              = link_to root_path do
                = image_tag 'logo-compliments.svg', alt: 'Compliments'
              = link_to quotes_path, class: 'por rn20' do
                = image_tag 'logo-quotes-text.svg', alt: 'Quotes'
            - else
              = link_to quotes_path do
                = image_tag 'logo-quotes.svg', alt: 'Quotes'
              = link_to root_path, class: 'por rn20' do
                = image_tag 'logo-compliments-text.svg', alt: 'Compliments'
          .g-b.g-b--1of2
            - if current_user
              = image_tag current_user.image, class: "thumb fr", height: "50", width: "50"

    %main.row.content
      .cell.well
        = yield

    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/big_screen.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Compliments
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag('https://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700')
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
  %body{ class: body_class }
    %header.row.row--a.header
      .cell.well
        %h1.tac #compliments

    %main.row.content
      .cell.well
        = yield

    = javascript_include_tag 'application', 'data-turbolinks-track' => true